import { pgTable, text, numeric, timestamp, uuid, jsonb, integer } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

export const ebayListings = pgTable("ebay_listings", {
  id: uuid("id").defaultRandom().primaryKey(),
  ebayItemId: text("ebay_item_id").notNull().unique(),
  sellerSku: text("seller_sku"),
  ebaySku: text("ebay_sku"),
  barcode: text("barcode"),
  title: text("title").notNull(),
  subtitle: text("subtitle"),
  description: text("description"),
  currentPrice: numeric("current_price", { precision: 10, scale: 2 }),
  currency: text("currency").default("USD"),
  listingStatus: text("listing_status"),
  listingType: text("listing_type"),
  quantity: integer("quantity"),
  availableQuantity: integer("available_quantity"),
  viewCount: integer("view_count"),
  watchCount: integer("watch_count"),
  conditionId: integer("condition_id"),
  conditionDescription: text("condition_description"),
  categoryId: text("category_id"),
  categoryName: text("category_name"),
  imageUrls: jsonb("image_urls").$type<string[]>(),
  returnPolicy: jsonb("return_policy"),
  shippingDetails: jsonb("shipping_details"),
  paymentMethods: text("payment_methods").array(),
  startTime: timestamp("start_time"),
  endTime: timestamp("end_time"),
  itemUrl: text("item_url"),
  createdAt: timestamp("created_at").default(sql`CURRENT_TIMESTAMP`),
  updatedAt: timestamp("updated_at").default(sql`CURRENT_TIMESTAMP`),
  rawData: jsonb("raw_data"),
});
