CREATE TABLE "ebay_listings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ebay_item_id" text NOT NULL,
	"seller_sku" text,
	"ebay_sku" text,
	"barcode" text,
	"title" text NOT NULL,
	"subtitle" text,
	"description" text,
	"current_price" numeric(10, 2),
	"currency" text DEFAULT 'USD',
	"listing_status" text,
	"listing_type" text,
	"quantity" integer,
	"available_quantity" integer,
	"view_count" integer,
	"watch_count" integer,
	"condition_id" integer,
	"condition_description" text,
	"category_id" text,
	"category_name" text,
	"image_urls" jsonb,
	"return_policy" jsonb,
	"shipping_details" jsonb,
	"payment_methods" text[],
	"start_time" timestamp,
	"end_time" timestamp,
	"item_url" text,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"raw_data" jsonb,
	CONSTRAINT "ebay_listings_ebay_item_id_unique" UNIQUE("ebay_item_id")
);
