CREATE TABLE "amazon_products" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"asin" text NOT NULL,
	"seller_sku" text,
	"product_barcode" text,
	"title" text,
	"brand" text,
	"manufacturer" text,
	"product_group" text,
	"product_status" text,
	"variation_theme" text,
	"parent_asin" text,
	"fulfillment_channels" text[],
	"price" numeric(10, 2),
	"currency" text DEFAULT 'USD',
	"offers" jsonb,
	"images" jsonb,
	"item_attributes" jsonb,
	"item_dimensions" jsonb,
	"package_dimensions" jsonb,
	"sales_rank" jsonb,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"raw_data" jsonb,
	CONSTRAINT "amazon_products_asin_unique" UNIQUE("asin")
);
