CREATE TABLE "etsy_listings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"etsy_listing_id" numeric(18, 0) NOT NULL,
	"seller_user_id" numeric(18, 0),
	"seller_sku" text,
	"barcode" text,
	"title" text NOT NULL,
	"description" text,
	"price" numeric(10, 2),
	"currency" text DEFAULT 'USD',
	"quantity" integer,
	"listing_status" text,
	"url" text,
	"views" integer,
	"num_favorers" integer,
	"tags" text[],
	"materials" text[],
	"is_customizable" text,
	"has_variations" text,
	"variations" jsonb,
	"images" jsonb,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"original_creation_tsz" timestamp,
	"last_modified_tsz" timestamp,
	"raw_data" jsonb,
	CONSTRAINT "etsy_listings_etsy_listing_id_unique" UNIQUE("etsy_listing_id")
);
