CREATE TABLE "woocommerce_products" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"wc_product_id" bigint NOT NULL,
	"seller_sku" text,
	"barcode" text,
	"name" text NOT NULL,
	"slug" text,
	"permalink" text,
	"type" text,
	"status" text,
	"description" text,
	"short_description" text,
	"price" numeric(10, 2),
	"regular_price" numeric(10, 2),
	"sale_price" numeric(10, 2),
	"stock_quantity" integer,
	"stock_status" text,
	"currency" text DEFAULT 'USD',
	"images" jsonb,
	"categories" jsonb,
	"tags" jsonb,
	"attributes" jsonb,
	"variations" bigint[],
	"date_on_sale_from" timestamp,
	"date_on_sale_to" timestamp,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"raw_data" jsonb,
	CONSTRAINT "woocommerce_products_wc_product_id_unique" UNIQUE("wc_product_id")
);
